name: autd3
description: "autd3 lightweight library"
version: 27.0.0
homepage: https://github.com/shinolab/autd3

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: 3.22.2

dependencies:
  fixnum: ^1.1.0
  flutter:
    sdk: flutter
  grpc: ^4.0.0
  protobuf: ^3.1.0
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
