name: coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
 coverage:
  name: coverage
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version-file: pubspec.yaml
    - run: flutter test --coverage    
    - run: |
        sudo apt-get update
        sudo apt-get -y install lcov
    - run: |
          lcov --remove coverage/lcov.info 'lib/src/generated/*'  -o ./coverage/lcov-new.info
    - uses: codecov/codecov-action@v4.0.1
      with:
        disable_search: true
        file: ./coverage/lcov-new.info
        token: ${{ secrets.CODECOV_TOKEN }}
