name: coverage

on:
  push:
    branches:
      - 'develop'

jobs:
 coverage:
  name: coverage
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - name: set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version-file: pubspec.yaml
    - name: test
      run: flutter test --coverage    
    - name: Install lcov
      run: |
        sudo apt-get update
        sudo apt-get -y install lcov
    - name: omit generated code from coverage
      run: |
          lcov --remove coverage/lcov.info 'lib/src/generated/*'  -o ./coverage/lcov-new.info
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        disable_search: true
        file: ./coverage/lcov-new.info
        token: ${{ secrets.CODECOV_TOKEN }}
